default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: "root"
  password: password
  host: localhost

development:
  <<: *default
  database: exam_word_development
  socket: /var/run/mysqld/mysqld.sock

test:
  <<: *default
  database: exam_word_development_test

production:
  <<: *default
  database: <%= ENV.fetch('DB_DATABASE', '') %>
  username: <%= ENV.fetch("DB_USER", "root") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  host: <%= ENV.fetch('DB_HOSTNAME', '') %>
  port: <%= ENV.fetch('DB_PORT', 3306) %>
  socket: /var/run/mysqld/mysqld.sock

