development:
  adapter: mysql2
  database: exam_word_development
  username: root
  password: password

test:
  adapter: mysql2
  database: exam_word_development_test
  username: root
  password: password
